### PR TITLE
Fix empty scalefactors in model 125

### PR DESCRIPTION
**Pull request by cfstras**
Fixes https://github.com/sunspec/models/issues/32

### CODE REVIEW

**Comment by altendky** [comment]
@cfstras, is this urgent for you?  Or can we wait a few days to see where sunspec/models#39 goes?  The change seems fine so if you follow my own workflow with an official PR (and mention me) I'll go ahead and merge it asap.

**Comment by altendky** [comment]
Kick CI

**Comment by cfstras** [comment]
nope, not urgent.
I realized I had seen your workflow before about a minute after opening the PR, but the figured we wait to hear about sunspec#39, as you suggested.

**Comment by cfstras** [comment]
moved to sunspec repo: https://github.com/sunspec/models/pull/40

**Pull request closed without merging**
